---
http:
  routers:
    traefik:
      rule: "Host(`traefik.docker.localhost`"
      service: "api@internal"
      tls:
        domains:
          - main: "docker.localhost"
            sans: 
              - "*.docker.localhost"

tls:
  certificates:
    - certfile: "/etc/certs/local-cert.pem"
    - keyfile: "/etc/certs/local-cert.key"
...
